# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XF26-rOqlrflQQCs1f50WmIHH_vlTfMw
"""

print('I love MTUCI')