name: ETL Workflow

on:
  push:
    branches:
      - main

jobs:
  ETL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Extract Data
        run: echo "1,2,3,4,5" > data.txt
      
      - name: Transform Data
        run: |
          input=$(<data.txt)
          transformed=$(echo "$input" | tr ',' '\n' | awk '{print $1 * 10}' | paste -sd "," -)
          echo "$transformed" > transformed_data.txt
      
      - name: Load Data
        run: |
          while IFS=',' read -r item; do
            echo "Loading item: $item"
          done < transformed_data.txt
